export const AppState = {
  WALLET_REQUIRED: 'WALLET_REQUIRED',
  NETWORK_UNSUPPORTED: 'NETWORK_UNSUPPORTED',
  CONTRACT_VERIFICATION: 'CONTRACT_VERIFICATION',
  CONTRACT_LOADING: 'CONTRACT_LOADING',
  CONTRACT_NOT_DEPLOYED: 'CONTRACT_NOT_DEPLOYED',
  AWAITING_INPUT: 'AWAITING_INPUT',
  READY_TO_DISPERSE: 'READY_TO_DISPERSE',
} as const

export type AppState = typeof AppState[keyof typeof AppState]