name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./wagmi-disperse

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: ./wagmi-disperse/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm run lint

      - name: Run tests
        run: pnpm test -- --run

      - name: Run build
        run: pnpm run build

  build-check:
    name: Build Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./wagmi-disperse

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
          cache-dependency-path: ./wagmi-disperse/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Type check
        run: pnpm exec tsc --noEmit

      - name: Build
        run: pnpm run build

      - name: Check bundle size
        run: |
          echo "Bundle sizes:"
          ls -lah dist/assets/*.js | grep -E '\.(js|css)$'